name: CI
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linters / tests
        run: |
          npm ci
          npm run lint
          npm run test
      - name: Build
        run: npm run build
      - name: Deploy to staging
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/var/www/staging/"
